<a href="https://colab.research.google.com/github/ErickNoGit/Exerc-cios/blob/main/Exerc%C3%ADcios_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [502]:
import pandas as pd

# Exercício 1:
Considere o seguinte DataFrame 'df' com dados sobre alunos:

In [503]:
data_1 = {
    'Nome': ['Alice', 'Bob', 'Carol', 'David', 'Eva'],
    'Idade': [25, 22, 23, 24, 26],
    'Curso': ['Engenharia', 'Direito', 'Medicina', 'Economia', 'Administração'],
    'Nota': [7.8, 6.5, 8.9, 6.2, 9.1]
}

df_1 = pd.DataFrame(data_1)
display(df_1)

    Nome  Idade          Curso  Nota
0  Alice     25     Engenharia   7.8
1    Bob     22        Direito   6.5
2  Carol     23       Medicina   8.9
3  David     24       Economia   6.2
4    Eva     26  Administração   9.1

a) Imprima as primeiras 3 linhas do DataFrame.

In [504]:
# RESPOSTA 1 LETRA A

# Exercício 2:
Considere o seguinte DataFrame 'df' com informações sobre vendas:

In [505]:
data_2 = {
    'Produto': ['Camiseta', 'Calça', 'Boné', 'Shorts', 'Meia'],
    'Quantidade': [100, 80, 50, 120, 200],
    'Preço Unitário': [25.99, 39.99, 15.00, 29.99, 9.99]
}

df_2 = pd.DataFrame(data_2)
display(df_2)

    Produto  Quantidade  Preço Unitário
0  Camiseta         100           25.99
1     Calça          80           39.99
2      Boné          50           15.00
3    Shorts         120           29.99
4      Meia         200            9.99

a) Calcule o total de vendas (Quantidade x Preço Unitário) e adicione uma coluna 'Total' ao DataFrame.

In [506]:
# RESPOSTA 2 LETRA A

# Exercício 3:
Considere o seguinte DataFrame 'df' com dados de temperatura em diferentes cidades:

In [507]:
data_3 = {
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Brasília', 'Salvador'],
    'Temperatura (C)': [28, 30, 26, 32, 34]
}

df_3 = pd.DataFrame(data_3)
display(df_3)

           Cidade  Temperatura (C)
0       São Paulo               28
1  Rio de Janeiro               30
2  Belo Horizonte               26
3        Brasília               32
4        Salvador               34

a) Imprima a temperatura média das cidades.

In [508]:
# RESPOSTA 3 LETRA A

# Exercício 4:
Considere o seguinte DataFrame 'df' com informações sobre filmes:

In [509]:
data_4 = {
    'Título': ['Filme A', 'Filme B', 'Filme C', 'Filme D', 'Filme E'],
    'Gênero': ['Ação', 'Comédia', 'Drama', 'Aventura', 'Ficção Científica'],
    'Ano de Lançamento': [2010, 2015, 2012, 2018, 2020],
    'Bilheteria (milhões USD)': [300, 150, 200, 450, 350]
}

df_4 = pd.DataFrame(data_4)
display(df_4)

    Título             Gênero  Ano de Lançamento  Bilheteria (milhões USD)
0  Filme A               Ação               2010                       300
1  Filme B            Comédia               2015                       150
2  Filme C              Drama               2012                       200
3  Filme D           Aventura               2018                       450
4  Filme E  Ficção Científica               2020                       350

a) Ordene o DataFrame em ordem decrescente de bilheteria.

In [510]:
# RESPOSTA 4 LETRA A

# Exercício 5:
Considere o seguinte DataFrame 'df' com dados de funcionários:

In [511]:
data_5 = {
    'Nome': ['Ana', 'Luiz', 'Mariana', 'Pedro', 'Carla'],
    'Cargo': ['Analista', 'Gerente', 'Analista', 'Coordenador', 'Diretor'],
    'Salário': [4500, 6000, 4200, 7000, 10000]
}

df_5 = pd.DataFrame(data_5)
display(df_5)

      Nome        Cargo  Salário
0      Ana     Analista     4500
1     Luiz      Gerente     6000
2  Mariana     Analista     4200
3    Pedro  Coordenador     7000
4    Carla      Diretor    10000

a) Crie um novo DataFrame contendo apenas os funcionários que possuem salário acima de 5000.

In [512]:
# RESPOSTA 5 LETRA A

# Exercício 6:
Considere o seguinte DataFrame 'df' com informações sobre alunos:

In [513]:
data_6 = {
    'Nome': ['Ana', 'Luiz', 'Mariana', 'Pedro', 'Carla'],
    'Idade': [25, 28, 22, 24, 26],
    'Curso': ['Engenharia', 'Administração', 'Direito', 'Medicina', 'Economia'],
    'Nota1': [7.5, 6.2, 8.9, 9.1, 6.8],
    'Nota2': [6.8, 8.5, 7.2, 6.5, 9.0]
}

df_6 = pd.DataFrame(data_6)
display(df_6)

      Nome  Idade          Curso  Nota1  Nota2
0      Ana     25     Engenharia    7.5    6.8
1     Luiz     28  Administração    6.2    8.5
2  Mariana     22        Direito    8.9    7.2
3    Pedro     24       Medicina    9.1    6.5
4    Carla     26       Economia    6.8    9.0

a) Calcule a média das notas (Nota1 e Nota2) para cada aluno e adicione uma coluna 'Média' ao DataFrame.

In [514]:
# RESPOSTA 6 LETRA A

# Exercício 7:
Considere o seguinte DataFrame 'df' com informações sobre produtos:

In [515]:
data_7 = {
    'Produto': ['Camiseta', 'Calça', 'Boné', 'Shorts', 'Meia'],
    'Quantidade': [100, 80, 50, 120, 200],
    'Preço Unitário': [25.99, 39.99, 15.00, 29.99, 9.99],
    'Desconto (%)': [10, 15, 5, 20, 12]
}

df_7 = pd.DataFrame(data_7)
display(df_7)

    Produto  Quantidade  Preço Unitário  Desconto (%)
0  Camiseta         100           25.99            10
1     Calça          80           39.99            15
2      Boné          50           15.00             5
3    Shorts         120           29.99            20
4      Meia         200            9.99            12

a) Calcule o valor total (considerando o desconto) para cada produto e adicione uma coluna 'Valor Total' ao DataFrame.

In [516]:
# RESPOSTA 7 LETRA A

# Exercício 8:
Considere o seguinte DataFrame 'df' com informações sobre funcionários

In [517]:
data_8 = {
    'Nome': ['Ana', 'Luiz', 'Mariana', 'Pedro', 'Carla'],
    'Cargo': ['Analista', 'Gerente', 'Analista', 'Coordenador', 'Diretor'],
    'Salário': [4500, 6000, 4200, 7000, 10000]
}

df_8 = pd.DataFrame(data_8)
display(df_8)

      Nome        Cargo  Salário
0      Ana     Analista     4500
1     Luiz      Gerente     6000
2  Mariana     Analista     4200
3    Pedro  Coordenador     7000
4    Carla      Diretor    10000

a) Ordene o DataFrame em ordem alfabética crescente pelo nome dos funcionários.

In [518]:
# RESPOSTA 8 LETRA A

# Exercício 9:
Considere o seguinte DataFrame 'df' com informações sobre alunos:

In [519]:
data_9 = {
    'Nome': ['Ana', 'Luiz', 'Mariana', 'Pedro', 'Carla'],
    'Idade': [25, 28, 22, 24, 26],
    'Curso': ['Engenharia', 'Administração', 'Direito', 'Medicina', 'Economia'],
    'Nota1': [7.5, 6.2, 8.9, 9.1, 6.8],
    'Nota2': [6.8, 8.5, 7.2, 6.5, 9.0]
}

df_9 = pd.DataFrame(data_9)
display(df_9)

      Nome  Idade          Curso  Nota1  Nota2
0      Ana     25     Engenharia    7.5    6.8
1     Luiz     28  Administração    6.2    8.5
2  Mariana     22        Direito    8.9    7.2
3    Pedro     24       Medicina    9.1    6.5
4    Carla     26       Economia    6.8    9.0

a) Crie uma nova coluna 'Situação' no DataFrame, onde será 'Aprovado' se a média das notas for maior ou igual a 7.0, e 'Reprovado' caso contrário.

In [520]:
# RESPOSTA 9 LETRA A

# Exercício 10:
Considere o seguinte DataFrame 'df' com informações sobre vendas:

In [521]:
data_10 = {
    'Produto': ['Camiseta', 'Calça', 'Boné', 'Shorts', 'Meia'],
    'Quantidade': [100, 80, 50, 120, 200],
    'Preço Unitário': [25.99, 39.99, 15.00, 29.99, 9.99]
}

df_10 = pd.DataFrame(data_10)
display(df_10)

    Produto  Quantidade  Preço Unitário
0  Camiseta         100           25.99
1     Calça          80           39.99
2      Boné          50           15.00
3    Shorts         120           29.99
4      Meia         200            9.99

a) Calcule o valor total das vendas (Quantidade x Preço Unitário) e adicione uma coluna 'Total' ao DataFrame.

In [522]:
# RESPOSTA 10 LETRA A

# Exercício 11:
Considere o seguinte dicionário com dados de vendas de produtos em uma loja:

In [523]:
data_11 = {
    'Produto': ['Camiseta', 'Calça', 'Chinelo', 'Boné', 'Meia'],
    'Preço': [25.99, 49.99, 15.00, 12.50, 7.99],
    'Quantidade': [50, 30, 80, 20, 100]
}

df_11 = pd.DataFrame(data_11)
display(df_11)

    Produto  Preço  Quantidade
0  Camiseta  25.99          50
1     Calça  49.99          30
2   Chinelo  15.00          80
3      Boné  12.50          20
4      Meia   7.99         100

a) Exiba as informações estatísticas básicas do DataFrame.

In [524]:
# RESPOSTA 11 LETRA A

b) Calcule o total de vendas (Preço * Quantidade) para cada produto e adicione como uma nova coluna chamada "Total", depois exiba informações estatísticas básicas.

In [525]:
# RESPOSTA 11 LETRA B

# Exercício 12:
Crie um DataFrame com informações de alunos e suas respectivas notas em diferentes matérias:

In [526]:
data_12 = {
    'Aluno': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'Matemática': [7.5, 8.2, 6.8, 9.0, 7.1],
    'História': [6.2, 5.5, 7.8, 8.5, 6.9],
    'Geografia': [8.0, 7.5, 8.2, 6.7, 7.8]
}

df_12 = pd.DataFrame(data_12)
display(df_12)

   Aluno  Matemática  História  Geografia
0   João         7.5       6.2        8.0
1  Maria         8.2       5.5        7.5
2  Pedro         6.8       7.8        8.2
3    Ana         9.0       8.5        6.7
4  Lucas         7.1       6.9        7.8

a) Exiba as informações dos alunos que obtiveram média acima de 7.0 em todas as disciplinas.

In [527]:
# RESPOSTA 12 LETRA A

# Exercício 13:
Crie um DataFrame com informações sobre vendas em diferentes filiais:

In [528]:
data_13 = {
    'Filial': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Vendas': [5000, 6200, 4500, 5500, 5800, 4200],
    'Despesas': [3000, 3400, 2800, 3200, 3500, 2700]
}

df_13 = pd.DataFrame(data_13)
display(df_13)

  Filial  Vendas  Despesas
0      A    5000      3000
1      B    6200      3400
2      C    4500      2800
3      A    5500      3200
4      B    5800      3500
5      C    4200      2700

a) Calcule o lucro (Vendas - Despesas) para cada filial e adicione como uma nova coluna chamada "Lucro".

In [529]:
# RESPOSTA 13 LETRA A

b) Exiba a filial que obteve o maior lucro.

In [530]:
# RESPOSTA 13 LETRA B

# Exercício 14:
Crie um DataFrame com informações de funcionários de uma empresa:

In [531]:
data_14 = {
    'Nome': ['Ana', 'João', 'Maria', 'Pedro', 'Carla'],
    'Idade': [28, 34, 25, 30, 22],
    'Cargo': ['Analista', 'Gerente', 'Estagiário', 'Coordenador', 'Assistente'],
    'Salário': [4500, 7000, 2500, 6000, 3000]
}

df_14 = pd.DataFrame(data_14)
display(df_14)

    Nome  Idade        Cargo  Salário
0    Ana     28     Analista     4500
1   João     34      Gerente     7000
2  Maria     25   Estagiário     2500
3  Pedro     30  Coordenador     6000
4  Carla     22   Assistente     3000

a) Exiba os funcionários que têm salário acima de 4000.

In [532]:
# RESPOSTA 14 LETRA A

b) Calcule a média de idade dos funcionários de cada cargo.

In [533]:
# RESPOSTA 15 LETRA B

# Exercício 15:
Crie um DataFrame com informações sobre o desempenho de jogadores em um jogo:

In [534]:
data_15 = {
    'Jogador': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'Pontuação': [150, 210, 180, 190, 160],
    'Nível': ['Intermediário', 'Avançado', 'Avançado', 'Intermediário', 'Iniciante'],
    'Tempo_Jogado': [10.5, 15.2, 12.7, 14.3, 9.8]
}

df_15 = pd.DataFrame(data_15)
display(df_15)

  Jogador  Pontuação          Nível  Tempo_Jogado
0    João        150  Intermediário          10.5
1   Maria        210       Avançado          15.2
2   Pedro        180       Avançado          12.7
3     Ana        190  Intermediário          14.3
4   Lucas        160      Iniciante           9.8

a) Exiba os jogadores que estão no nível "Avançado" e têm pontuação acima de 200.

In [535]:
# RESPOSTA 15 LETRA A

b) Calcule o tempo médio jogado por nível de habilidade (Nível).

In [536]:
# RESPOSTA 15 LETRA B0

# Exercício 16:
Crie um DataFrame com informações sobre vendas de diferentes produtos em diferentes datas:

In [537]:
data_16 = {
    'Data': ['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04', '2023-07-05'],
    'Produto': ['Camiseta', 'Boné', 'Chinelo', 'Calça', 'Meia'],
    'Quantidade': [50, 20, 80, 30, 100],
    'Valor_Unitario': [25.99, 12.50, 15.00, 49.99, 7.99]
}

df_16 = pd.DataFrame(data_16)
display(df_16)

         Data   Produto  Quantidade  Valor_Unitario
0  2023-07-01  Camiseta          50           25.99
1  2023-07-02      Boné          20           12.50
2  2023-07-03   Chinelo          80           15.00
3  2023-07-04     Calça          30           49.99
4  2023-07-05      Meia         100            7.99

a) Converta a coluna "Data" para o tipo datetime.

In [538]:
# RESPOSTA 16 LETRA A

b) Calcule o total de vendas (Quantidade * Valor_Unitario) para cada produto e adicione como uma nova coluna chamada "Total_Vendas".

In [539]:
# RESPOSTA 16 LETRA B
df_16['Total_Vendas'] = df_16['Quantidade'] * df_16['Valor_Unitario']
df_16

         Data   Produto  Quantidade  Valor_Unitario  Total_Vendas
0  2023-07-01  Camiseta          50           25.99        1299.5
1  2023-07-02      Boné          20           12.50         250.0
2  2023-07-03   Chinelo          80           15.00        1200.0
3  2023-07-04     Calça          30           49.99        1499.7
4  2023-07-05      Meia         100            7.99         799.0

# Exercício 17:
Crie um DataFrame com informações sobre alunos e suas respectivas notas em diferentes matérias:

In [540]:
data_17 = {
    'Aluno': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'Matemática': [7.5, 8.2, 6.8, 9.0, 7.1],
    'História': [6.2, 5.5, 7.8, 8.5, 6.9],
    'Geografia': [8.0, 7.5, 8.2, 6.7, 7.8]
}

df_17 = pd.DataFrame(data_17)
display(df_17)

   Aluno  Matemática  História  Geografia
0   João         7.5       6.2        8.0
1  Maria         8.2       5.5        7.5
2  Pedro         6.8       7.8        8.2
3    Ana         9.0       8.5        6.7
4  Lucas         7.1       6.9        7.8

a) Calcule a média de cada aluno e adicione como uma nova coluna chamada "Média_Geral".

In [541]:
# RESPOSTA 17 LETRA A

b) Exiba os alunos que têm média geral acima de 7.0.

In [542]:
# RESPOSTA 17 LETRA B

# Exercício 18:
Crie um DataFrame com informações sobre o faturamento e custos de uma empresa ao longo de diferentes trimestres:

In [543]:
data_18 = {
    'Trimestre': ['Q1', 'Q1', 'Q2', 'Q2', 'Q3', 'Q3', 'Q4', 'Q4'],
    'Ano': [2022, 2023, 2022, 2023, 2022, 2023, 2022, 2023],
    'Faturamento': [50000, 62000, 54000, 59000, 58000, 56000, 61000, 63000],
    'Custos': [30000, 34000, 31000, 33000, 32000, 31000, 33000, 35000]
}

df_18 = pd.DataFrame(data_18)
display(df_18)

  Trimestre   Ano  Faturamento  Custos
0        Q1  2022        50000   30000
1        Q1  2023        62000   34000
2        Q2  2022        54000   31000
3        Q2  2023        59000   33000
4        Q3  2022        58000   32000
5        Q3  2023        56000   31000
6        Q4  2022        61000   33000
7        Q4  2023        63000   35000

a) Calcule o lucro (Faturamento - Custos) para cada trimestre e adicione como uma nova coluna chamada "Lucro".

In [544]:
# RESPOSTA 18 LETRA A

b) Exiba o trimestre em que o lucro foi maior.

In [545]:
# RESPOSTA 18 LETRA B

# Exercício 19:
Crie um DataFrame com informações sobre funcionários de diferentes departamentos:

In [546]:
data_19 = {
    'Nome': ['Ana', 'João', 'Maria', 'Pedro', 'Carla'],
    'Idade': [28, 34, 25, 30, 22],
    'Cargo': ['Analista', 'Gerente', 'Estagiário', 'Coordenador', 'Assistente'],
    'Salário': [4500, 7000, 2500, 6000, 3000],
    'Departamento': ['RH', 'Comercial', 'RH', 'TI', 'Comercial']
}

df_19 = pd.DataFrame(data_19)
display(df_19)

    Nome  Idade        Cargo  Salário Departamento
0    Ana     28     Analista     4500           RH
1   João     34      Gerente     7000    Comercial
2  Maria     25   Estagiário     2500           RH
3  Pedro     30  Coordenador     6000           TI
4  Carla     22   Assistente     3000    Comercial

a) Exiba os funcionários que têm salário acima de 4000 e trabalham no departamento "RH".

In [547]:
# RESPOSTA 19 LETRA A

b) Calcule a média salarial por departamento.

In [548]:
# RESPOSTA 19 LETRA B

# Exercício 20:
Crie um DataFrame com informações sobre o desempenho de jogadores em diferentes partidas:

In [549]:
data_20 = {
    'Jogador': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'Partida_1': [150, 210, 180, 190, 160],
    'Partida_2': [140, 220, 190, 200, 180],
    'Partida_3': [160, 230, 200, 210, 190]
}

df_20 = pd.DataFrame(data_20)
display(df_20)

  Jogador  Partida_1  Partida_2  Partida_3
0    João        150        140        160
1   Maria        210        220        230
2   Pedro        180        190        200
3     Ana        190        200        210
4   Lucas        160        180        190

a) Calcule a pontuação média de cada jogador.

In [550]:
# RESPOSTA 20 LETRA A

b) Exiba o jogador que obteve a maior pontuação total considerando todas as partidas.

In [551]:
# RESPOSTA 20 LETRA B

# Exercício 21:

In [552]:
dados_21 = {
    'Loja': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Produto': ['A', 'B', 'C', 'D', 'E', 'A', 'C', 'D', 'E'],
    'Vendedor': ['João', 'Maria', 'João', 'Pedro', 'Maria', 'Ana', 'Pedro', 'Maria', 'João'],
    'Valor': [100, 150, 200, 120, 80, 110, 170, 90, 130]
}

df_21 = pd.DataFrame(dados_21)
df_21

  Loja Produto Vendedor  Valor
0    A       A     João    100
1    B       B    Maria    150
2    C       C     João    200
3    A       D    Pedro    120
4    B       E    Maria     80
5    C       A      Ana    110
6    A       C    Pedro    170
7    B       D    Maria     90
8    C       E     João    130

a) Qual é o valor total de vendas realizado por cada loja?

In [553]:
# RESPOSTA 21 LETRA A

b) Qual é o valor total de vendas realizado por cada vendedor?

In [554]:
# RESPOSTA 21 LETRA B

c) Qual é a média de vendas por produto?

In [555]:
# RESPOSTA 21 LETRA C

# Exercício 22:

In [556]:
dados_22 = {
    'Cliente': ['João', 'Maria', 'Pedro', 'Ana', 'Luiza', 'Mariana', 'Lucas', 'Isabela', 'Pedro'],
    'Idade': [30, 25, 22, 35, 28, 40, 26, 33, 22],
    'Sexo': ['M', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'M'],
    'Estado Civil': ['Casado', 'Solteiro', 'Solteiro', 'Casado', 'Solteiro', 'Casado', 'Solteiro', 'Casado', 'Solteiro']
}

df_22 = pd.DataFrame(dados_22)
display(df_22)

   Cliente  Idade Sexo Estado Civil
0     João     30    M       Casado
1    Maria     25    F     Solteiro
2    Pedro     22    M     Solteiro
3      Ana     35    F       Casado
4    Luiza     28    F     Solteiro
5  Mariana     40    F       Casado
6    Lucas     26    M     Solteiro
7  Isabela     33    F       Casado
8    Pedro     22    M     Solteiro

a) Quantos clientes são do sexo masculino e quantos são do sexo feminino?

In [557]:
# RESPOSTA 22 LETRA A

b) Qual é a média de idade dos clientes?

In [558]:
# RESPOSTA 22 LETRA B

c) Crie uma nova coluna no DataFrame chamada **Faixa Etária**, que classifique os clientes em "Jovem" (idade até 25), "Adulto" (idade entre 26 e 40) e "Idoso" (idade acima de 40).

In [559]:
# RESPOSTA 22 LETRA C

# Exercício 23:

In [560]:
dados_23 = {
    'Loja': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Produto': ['A', 'B', 'C', 'D', 'E', 'A', 'C', 'D', 'E'],
    'Vendedor': ['João', 'Maria', 'João', 'Pedro', 'Maria', 'Ana', 'Pedro', 'Maria', 'João'],
    'Valor': [100, 150, 200, 120, 80, 110, 170, 90, 130]
}

df_23 = pd.DataFrame(dados_23)
display(df_23)

  Loja Produto Vendedor  Valor
0    A       A     João    100
1    B       B    Maria    150
2    C       C     João    200
3    A       D    Pedro    120
4    B       E    Maria     80
5    C       A      Ana    110
6    A       C    Pedro    170
7    B       D    Maria     90
8    C       E     João    130

a) Qual é o valor total de vendas realizado por cada loja?

In [561]:
# RESPOSTA 23 LETRA A

b) Qual é o valor total de vendas realizado por cada vendedor?

In [562]:
# RESPOSTA 23 LETRA B

c) Qual é a média de vendas por produto?

In [563]:
# RESPOSTA 23 LETRA C

# Exercício 24:

Considere o seguinte DataFrame df_exercicio24:

In [564]:
data_24 = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Idade': [28, 34, 29, 42, 26],
    'Salário': [5000, 6000, 4500, 8000, 5500]
}

df_24 = pd.DataFrame(data_24)
display(df_24)

      Nome  Idade  Salário
0    Alice     28     5000
1      Bob     34     6000
2  Charlie     29     4500
3    David     42     8000
4     Emma     26     5500

a) Selecione os funcionários com idade superior a 30.

In [565]:
# RESPOSTA 24 LETRA A

b) Calcule a média salarial dos funcionários com idade inferior a 30.

In [566]:
# RESPOSTA 24 LETRA B

# Exercício 25:

Considere o seguinte DataFrame df_25:

In [567]:
data_25 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos'],
    'Matemática': [8, 7, 10, 9, 6],
    'Português': [9, 6, 8, 10, 7],
    'História': [7, 8, 6, 9, 5]
}

df_25 = pd.DataFrame(data_25)
display(df_25)

    Aluno  Matemática  Português  História
0    João           8          9         7
1   Maria           7          6         8
2    José          10          8         6
3     Ana           9         10         9
4  Carlos           6          7         5

a) Crie uma nova coluna chamada "Média" que contenha a média das notas de cada aluno.

In [568]:
# RESPOSTA 25 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Média".

In [569]:
# RESPOSTA 25 LETRA B

# Exercício 26:

Considere o seguinte DataFrame df_26:

In [570]:
data_26 = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Vendas2019': [1000, 1200, 800, 950, 1100],
    'Vendas2020': [1050, 1250, 820, 900, 1150]
}

df_26 = pd.DataFrame(data_26)
display(df_26)

  Produto  Vendas2019  Vendas2020
0       A        1000        1050
1       B        1200        1250
2       C         800         820
3       D         950         900
4       E        1100        1150

a) Crie uma coluna chamada "Crescimento" que contenha a diferença percentual entre as vendas de 2020 e 2019 para cada produto.

In [571]:
# RESPOSTA 26 LETRA A

b) Identifique o produto que teve o maior crescimento de vendas.

In [572]:
# RESPOSTA 26 LETRA B

# Exercício 27:

Considere o seguinte DataFrame df_27:

In [573]:
data_27 = {
    'Data': ['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-05'],
    'Vendas': [1000, 1200, 800, 950, 1100]
}

df_27 = pd.DataFrame(data_27)
display(df_27)

         Data  Vendas
0  2023-06-01    1000
1  2023-06-02    1200
2  2023-06-03     800
3  2023-06-04     950
4  2023-06-05    1100

a) Converta a coluna 'Data' para o tipo datetime.

In [574]:
# RESPOSTA 27 LETRA A

b) Crie uma nova coluna chamada "Dia_da_Semana" que contenha o dia da semana (em formato texto) para cada data.

In [575]:
# RESPOSTA 27 LETRA B

# Exercício 28:

Considere o seguinte DataFrame df_28:

In [576]:
data_28 = {
    'Time': ['A', 'B', 'C', 'D', 'E'],
    'Gols': [3, 2, 2, 4, 1],
    'Contra': [2, 1, 3, 2, 4]
}

df_28 = pd.DataFrame(data_28)
display(df_28)

  Time  Gols  Contra
0    A     3       2
1    B     2       1
2    C     2       3
3    D     4       2
4    E     1       4

a) Crie uma nova coluna chamada "Saldo_de_Gols" que contenha a diferença entre os gols marcados e os gols sofridos por cada time.

In [577]:
# RESPOSTA 28 LETRA A

b) Identifique o time com o melhor saldo de gols.

In [578]:
# RESPOSTA 28 LETRA B

# Exercício 29:

Considere o seguinte DataFrame df_29:

In [579]:
data_29 = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Preço': [10, 20, 15, 25, 30],
    'Vendas': [100, 80, 120, 70, 90]
}

df_29 = pd.DataFrame(data_29)
display(df_29)

  Produto  Preço  Vendas
0       A     10     100
1       B     20      80
2       C     15     120
3       D     25      70
4       E     30      90

a) Crie uma nova coluna chamada **"Receita"** que contenha o valor total de receita (preço * vendas) para cada produto.

In [580]:
# RESPOSTA 29 LETRA A

b) Identifique o produto que gerou a maior receita.

In [581]:
# RESPOSTA 29 LETRA B

# Exercício 30:

Considere o seguinte DataFrame df_30:

In [582]:
data_30 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos'],
    'Faltas': [2, 3, 1, 4, 0],
    'Atrasos': [0, 1, 2, 0, 3]
}

df_30 = pd.DataFrame(data_30)
display(df_30)

    Aluno  Faltas  Atrasos
0    João       2        0
1   Maria       3        1
2    José       1        2
3     Ana       4        0
4  Carlos       0        3

a) Crie uma nova coluna chamada **"Total_Faltas_Atrasos"** que contenha a soma das faltas e atrasos para cada aluno.

In [583]:
# RESPOSTA 30 LETRA A

b) Identifique o aluno com o maior número total de faltas e atrasos.

In [584]:
# RESPOSTA 30 LETRA B

# Exercício 31:

Considere o seguinte DataFrame df_31:

In [585]:
data_31 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos'],
    'Nota1': [8, 7, 10, 9, 6],
    'Nota2': [9, 6, 8, 10, 7],
    'Nota3': [7, 8, 6, 9, 5]
}

df_31 = pd.DataFrame(data_31)
display(df_31)

    Aluno  Nota1  Nota2  Nota3
0    João      8      9      7
1   Maria      7      6      8
2    José     10      8      6
3     Ana      9     10      9
4  Carlos      6      7      5

a) Crie uma nova coluna chamada "Média_Final" que contenha a média final das notas de cada aluno (considere peso igual para todas as notas).

In [586]:
# RESPOSTA 31 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Média_Final".

In [587]:
# RESPOSTA 31 LETRA B

# Exercício 32:

Considere o seguinte DataFrame df_32:

In [588]:
data_32 = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Estoque': [100, 80, 120, 70, 90],
    'Vendas': [20, 30, 25, 40, 15]
}

df_32 = pd.DataFrame(data_32)
display(df_32)

  Produto  Estoque  Vendas
0       A      100      20
1       B       80      30
2       C      120      25
3       D       70      40
4       E       90      15

a) Crie uma nova coluna chamada **"Estoque_Atual"** que contenha a quantidade atual de produtos em estoque (Estoque - Vendas).

In [589]:
# RESPOSTA 32 LETRA A

b) Identifique o produto com o menor estoque atual.

In [590]:
# RESPOSTA 32 LETRA B

# Exercício 33:

Considere o seguinte DataFrame df_33:

In [591]:
data_33 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos'],
    'Faltas': [2, 3, 1, 4, 0],
    'Atrasos': [0, 1, 2, 0, 3],
    'Notas': [8, 7, 9, 6, 10]
}

df_33 = pd.DataFrame(data_33)
display(df_33)

    Aluno  Faltas  Atrasos  Notas
0    João       2        0      8
1   Maria       3        1      7
2    José       1        2      9
3     Ana       4        0      6
4  Carlos       0        3     10

a) Crie uma nova coluna chamada **"Nota_Final"** que contenha a média ponderada das notas dos alunos, considerando peso 2 para as notas e peso 1 para as faltas e atrasos.

In [592]:
# RESPOSTA 23 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Nota_Final".

In [593]:
# RESPOSTA 23 LETRA B

# Exercício 34:

Considere o seguinte DataFrame df_34:

In [594]:
data_34 = {
    'Time': ['A', 'B', 'C', 'D', 'E'],
    'Vitórias': [3, 2, 4, 1, 2],
    'Empates': [2, 3, 1, 3, 2],
    'Derrotas': [1, 2, 3, 2, 4]
}

df_34 = pd.DataFrame(data_34)
display(df_34)

  Time  Vitórias  Empates  Derrotas
0    A         3        2         1
1    B         2        3         2
2    C         4        1         3
3    D         1        3         2
4    E         2        2         4

a) Crie uma nova coluna chamada **"Pontuação"** que contenha a pontuação de cada time no campeonato, considerando 3 pontos por vitória, 1 ponto por empate e 0 pontos por derrota.

In [595]:
# RESPOSTA 34 LETRA A

b) Identifique o time com a maior pontuação.

In [596]:
# RESPOSTA 34 LETRA B

# Exercício 35:

Considere o seguinte DataFrame df_35:

In [597]:
data_35 = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Idade': [28, 34, 29, 42, 26],
    'Salário': [5000, 6000, 4500, 8000, 5500]
}

df_35 = pd.DataFrame(data_35)
display(df_35)

      Nome  Idade  Salário
0    Alice     28     5000
1      Bob     34     6000
2  Charlie     29     4500
3    David     42     8000
4     Emma     26     5500

a) Crie uma nova coluna chamada "Décimo_Terceiro" que contenha o valor do décimo terceiro salário de cada funcionário (salário * 1/12).

In [598]:
# RESPOSTA 35 LETRA A

b) Identifique o funcionário com o maior décimo terceiro salário.

In [599]:
# RESPOSTA 35 LETRA B

# Exercício 36:

Considere o seguinte DataFrame df_36:

In [600]:
data_36 = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Preço': [10, 20, 15, 25, 30],
    'Vendas': [100, 80, 120, 70, 90]
}

df_36 = pd.DataFrame(data_36)
display(df_36)

  Produto  Preço  Vendas
0       A     10     100
1       B     20      80
2       C     15     120
3       D     25      70
4       E     30      90

a) Crie uma nova coluna chamada "Receita" que contenha o valor total de receita (preço * vendas) para cada produto.

In [601]:
# RESPOSTA 36 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Receita".

In [602]:
# RESPOSTA 36 LETRA B

# Exercício 37:

Considere o seguinte DataFrame df_37:

In [603]:
data_37 = {
    'Data': ['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-05'],
    'Vendas': [1000, 1200, 800, 950, 1100]
}

df_37 = pd.DataFrame(data_37)
display(df_37)

         Data  Vendas
0  2023-06-01    1000
1  2023-06-02    1200
2  2023-06-03     800
3  2023-06-04     950
4  2023-06-05    1100

a) Converta a coluna 'Data' para o tipo datetime.

In [604]:
# RESPOSTA 37 LETRA A

b) Crie uma nova coluna chamada "Dia_da_Semana" que contenha o dia da semana (em formato texto) para cada data.

In [605]:
# RESPOSTA 37 LETRA B

# Exercício 38:

Considere o seguinte DataFrame df_38:

In [606]:
data_38 = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Estoque': [100, 80, 120, 70, 90],
    'Vendas': [20, 30, 25, 40, 15]
}

df_38 = pd.DataFrame(data_38)
display(df_38)

  Produto  Estoque  Vendas
0       A      100      20
1       B       80      30
2       C      120      25
3       D       70      40
4       E       90      15

a) Crie uma nova coluna chamada "Estoque_Atual" que contenha a quantidade atual de produtos em estoque (Estoque - Vendas).

In [607]:
# RESPOSTA 38 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Estoque_Atual".

In [608]:
# RESPOSTA 38 LETRA B

# Exercício 39:

Considere o seguinte DataFrame df_39:

In [609]:
data_39 = {
    'Time': ['A', 'B', 'C', 'D', 'E'],
    'Gols': [3, 2, 2, 4, 1],
    'Contra': [2, 1, 3, 2, 4]
}

df_39 = pd.DataFrame(data_39)
display(df_39)

  Time  Gols  Contra
0    A     3       2
1    B     2       1
2    C     2       3
3    D     4       2
4    E     1       4

a) Crie uma nova coluna chamada "Saldo_de_Gols" que contenha a diferença entre os gols marcados e os gols sofridos por cada time.

In [610]:
# RESPOSTA 39 LETRA A

b) Identifique o time com o melhor saldo de gols.

In [611]:
# RESPOSTA 39 LETRA B

# Exercício 40:

Considere o seguinte DataFrame df_40:

In [612]:
data_40 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos'],
    'Faltas': [2, 3, 1, 4, 0],
    'Atrasos': [0, 1, 2, 0, 3],
    'Notas': [8, 7, 9, 6, 10]
}

df_40 = pd.DataFrame(data_40)
display(df_40)

    Aluno  Faltas  Atrasos  Notas
0    João       2        0      8
1   Maria       3        1      7
2    José       1        2      9
3     Ana       4        0      6
4  Carlos       0        3     10

a) Crie uma nova coluna chamada "Nota_Final" que contenha a média ponderada das notas dos alunos, considerando peso 2 para as notas e peso 1 para as faltas e atrasos.

In [613]:
# RESPOSTA 40 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Nota_Final".

In [614]:
# RESPOSTA 40 LETRA B

# Exercício 41:

Considere o seguinte DataFrame df_41:

In [615]:
data_41 = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Gina'],
    'Idade': [28, 34, 29, 42, 26, 35, 31],
    'Salário': [5000, 6000, 4500, 8000, 5500, 7000, 5200]
}

df_41 = pd.DataFrame(data_41)
display(df_41)

      Nome  Idade  Salário
0    Alice     28     5000
1      Bob     34     6000
2  Charlie     29     4500
3    David     42     8000
4     Emma     26     5500
5    Frank     35     7000
6     Gina     31     5200

a) Selecione os funcionários com idade superior a 30.

In [616]:
# RESPOSTA 41 LETRA A

b) Calcule a média salarial dos funcionários com idade inferior a 30.

In [617]:
# RESPOSTA 41 LETRA B

c) Ordene o DataFrame em ordem crescente com base no salário.

In [618]:
# RESPOSTA 41 LETRA C

d) Adicione uma coluna chamada "Bônus" que contenha 10% do salário de cada funcionário.

In [619]:
# RESPOSTA 41 LETRA D

# Exercício 42:

Considere o seguinte DataFrame df_42:

In [620]:
data_42 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos', 'Lara', 'Pedro'],
    'Matemática': [8, 7, 10, 9, 6, 9, 8],
    'Português': [9, 6, 8, 10, 7, 7, 9],
    'História': [7, 8, 6, 9, 5, 8, 6]
}

df_42 = pd.DataFrame(data_42)
display(df_42)

    Aluno  Matemática  Português  História
0    João           8          9         7
1   Maria           7          6         8
2    José          10          8         6
3     Ana           9         10         9
4  Carlos           6          7         5
5    Lara           9          7         8
6   Pedro           8          9         6

a) Crie uma nova coluna chamada "Média" que contenha a média das notas de cada aluno.

In [621]:
# RESPOSTA 42 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Média".

In [622]:
# RESPOSTA 42 LETRA B



c) Identifique o aluno que obteve a maior nota em Matemática.

In [623]:
# RESPOSTA 42 LETRA C

d) Adicione uma coluna chamada "Situação" que contenha "Aprovado" para alunos com média >= 7 e "Reprovado" para alunos com média < 7.

In [624]:
# RESPOSTA 42 LETRA D

# Exercício 43:

Considere o seguinte DataFrame df_43:

In [625]:
data_43 = {
    'Produto': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
    'Vendas2019': [1000, 1200, 800, 950, 1100, 1300, 850, 920],
    'Vendas2020': [1050, 1250, 820, 900, 1150, 1350, 820, 950]
}

df_43 = pd.DataFrame(data_43)
display(df_43)

  Produto  Vendas2019  Vendas2020
0       A        1000        1050
1       B        1200        1250
2       C         800         820
3       D         950         900
4       E        1100        1150
5       F        1300        1350
6       G         850         820
7       H         920         950

a) Crie uma coluna chamada "Crescimento" que contenha a diferença percentual entre as vendas de 2020 e 2019 para cada produto.

In [626]:
# RESPOSTA 43 LETRA A

b) Identifique o produto que teve o menor crescimento de vendas.

In [627]:
# RESPOSTA 43 LETRA B

c) Adicione uma coluna chamada "Total_Vendas" que contenha a soma das vendas de 2019 e 2020 para cada produto.

In [628]:
# RESPOSTA 43 LETRA C

# Exercício 44:

Considere o seguinte DataFrame df_44:

In [629]:
data_44 = {
    'Data': ['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08'],
    'Vendas': [1000, 1200, 800, 950, 1100, 1300, 850, 920]
}

df_44 = pd.DataFrame(data_44)
display(df_44)

         Data  Vendas
0  2023-06-01    1000
1  2023-06-02    1200
2  2023-06-03     800
3  2023-06-04     950
4  2023-06-05    1100
5  2023-06-06    1300
6  2023-06-07     850
7  2023-06-08     920

a) Converta a coluna 'Data' para o tipo datetime.

In [630]:
# RESPOSTA 44 LETRA A

b) Crie uma nova coluna chamada "Dia_da_Semana" que contenha o dia da semana (em formato texto) para cada data.

In [631]:
# RESPOSTA 44 LETRA B

c) Identifique o dia da semana em que foram registradas as maiores vendas.

In [632]:
# RESPOSTA 44 LETRA C

# Exercício 45:

Considere o seguinte DataFrame df_45:

In [633]:
data_45 = {
    'Time': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
    'Gols': [3, 2, 2, 4, 1, 3, 2, 5],
    'Contra': [2, 1, 3, 2, 4, 2, 3, 4]
}

df_45 = pd.DataFrame(data_45)
display(df_45)

  Time  Gols  Contra
0    A     3       2
1    B     2       1
2    C     2       3
3    D     4       2
4    E     1       4
5    F     3       2
6    G     2       3
7    H     5       4

a) Crie uma nova coluna chamada "Saldo_de_Gols" que contenha a diferença entre os gols marcados e os gols sofridos por cada time.

In [634]:
# RESPOSTA 45 LETRA A

b) Identifique o time com o maior saldo de gols.

In [635]:
# RESPOSTA 45 LETRA B

c) Adicione uma coluna chamada "Aproveitamento" que contenha a porcentagem de aproveitamento de cada time (Gols / (Gols + Contra)).

In [636]:
# RESPOSTA 45 LETRA C

# Exercício 46:

Considere o seguinte DataFrame df_46:

In [637]:
data_46 = {
    'Produto': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
    'Preço': [10, 20, 15, 25, 30, 18, 22, 27],
    'Vendas': [100, 80, 120, 70, 90, 110, 75, 85]
}

df_46 = pd.DataFrame(data_46)
display(df_46)

  Produto  Preço  Vendas
0       A     10     100
1       B     20      80
2       C     15     120
3       D     25      70
4       E     30      90
5       F     18     110
6       G     22      75
7       H     27      85

a) Crie uma nova coluna chamada "Receita" que contenha o valor total de receita (preço * vendas) para cada produto.

In [638]:
# RESPOSTA 46 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Receita".

In [639]:
# RESPOSTA 46 LETRA B

c) Identifique o produto que gerou a menor receita.

In [640]:
# RESPOSTA 46 LETRA C

# Exercício 47:

Considere o seguinte DataFrame df_47:

In [641]:
data_47 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos', 'Lara', 'Pedro', 'Mariana'],
    'Faltas': [2, 3, 1, 4, 0, 2, 1, 3],
    'Atrasos': [0, 1, 2, 0, 3, 1, 0, 2],
    'Notas': [8, 7, 9, 6, 10, 9, 8, 7]
}

df_47 = pd.DataFrame(data_47)
display(df_47)

     Aluno  Faltas  Atrasos  Notas
0     João       2        0      8
1    Maria       3        1      7
2     José       1        2      9
3      Ana       4        0      6
4   Carlos       0        3     10
5     Lara       2        1      9
6    Pedro       1        0      8
7  Mariana       3        2      7

a) Crie uma nova coluna chamada "Nota_Final" que contenha a média ponderada das notas dos alunos, considerando peso 2 para as notas e peso 1 para as faltas e atrasos.

In [642]:
# RESPOSTA 47 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Nota_Final".

In [643]:
# RESPOSTA 47 LETRA B

c) Identifique o aluno com a maior nota final.

In [644]:
# RESPOSTA 47 LETRA C

# Exercício 48:

Considere o seguinte DataFrame df_48:

In [645]:
data_48 = {
    'Time': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'Gols': [3, 2, 2, 4, 1, 3, 2, 5, 3, 2],
    'Contra': [2, 1, 3, 2, 4, 2, 3, 4, 2, 3]
}

df_48 = pd.DataFrame(data_48)
display(df_48)

  Time  Gols  Contra
0    A     3       2
1    B     2       1
2    C     2       3
3    D     4       2
4    E     1       4
5    F     3       2
6    G     2       3
7    H     5       4
8    I     3       2
9    J     2       3

a) Crie uma nova coluna chamada "Saldo_de_Gols" que contenha a diferença entre os gols marcados e os gols sofridos por cada time.

In [646]:
# RESPOSTA 48 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Saldo_de_Gols".

In [647]:
# RESPOSTA 48 LETRA B

c) Identifique o time com o maior saldo de gols.

In [648]:
# RESPOSTA 48 LETRA C

d) Adicione uma coluna chamada "Aproveitamento" que contenha a porcentagem de aproveitamento de cada time (Gols / (Gols + Contra)).

In [649]:
# RESPOSTA 48 LETRA D

# Exercício 49:

Considere o seguinte DataFrame df_49:

In [650]:
data_49 = {
    'Produto': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'Estoque': [100, 80, 120, 70, 90, 110, 75, 85, 100, 110],
    'Vendas': [20, 30, 25, 40, 15, 28, 33, 18, 25, 30]
}

df_49 = pd.DataFrame(data_49)
display(df_49)

  Produto  Estoque  Vendas
0       A      100      20
1       B       80      30
2       C      120      25
3       D       70      40
4       E       90      15
5       F      110      28
6       G       75      33
7       H       85      18
8       I      100      25
9       J      110      30

a) Crie uma nova coluna chamada "Estoque_Atual" que contenha a quantidade atual de produtos em estoque (Estoque - Vendas).

In [651]:
# RESPOSTA 49 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Estoque_Atual".

In [652]:
# RESPOSTA 49 LETRA B

c) Identifique o produto que possui o menor estoque atual.

In [653]:
# RESPOSTA 49 LETRA C

d) Adicione uma coluna chamada "Disponibilidade" que contenha a porcentagem de produtos disponíveis em estoque (Estoque_Atual / Estoque).

In [654]:
# RESPOSTA 49 LETRA D

# Exercício 50:

Considere o seguinte DataFrame df_50:

In [655]:
data_50 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos', 'Lara', 'Pedro', 'Mariana', 'Paulo', 'Bianca'],
    'Faltas': [2, 3, 1, 4, 0, 2, 1, 3, 0, 1],
    'Atrasos': [0, 1, 2, 0, 3, 1, 0, 2, 1, 0],
    'Notas': [8, 7, 9, 6, 10, 9, 8, 7, 9, 8]
}

df_50 = pd.DataFrame(data_50)
display(df_50)

     Aluno  Faltas  Atrasos  Notas
0     João       2        0      8
1    Maria       3        1      7
2     José       1        2      9
3      Ana       4        0      6
4   Carlos       0        3     10
5     Lara       2        1      9
6    Pedro       1        0      8
7  Mariana       3        2      7
8    Paulo       0        1      9
9   Bianca       1        0      8

a) Crie uma nova coluna chamada "Nota_Final" que contenha a média ponderada das notas dos alunos, considerando peso 2 para as notas e peso 1 para as faltas e atrasos.

In [656]:
# RESPOSTA 50 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Nota_Final".

In [657]:
# RESPOSTA 50 LETRA B

c) Identifique o aluno com a maior nota final.

In [658]:
# RESPOSTA 50 LETRA C

d) Adicione uma coluna chamada "Situação" que contenha "Aprovado" para alunos com média >= 7 e "Reprovado" para alunos com média < 7.

In [659]:
# RESPOSTA 50 LETRA D

# Exercício 51:

Considere o seguinte DataFrame df_51:

In [660]:
data_51 = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Gina', 'Hannah', 'Ivan', 'Jack', 'Katie'],
    'Idade': [28, 34, 29, 42, 26, 35, 31, 38, 25, 33, 30],
    'Salário': [5000, 6000, 4500, 8000, 5500, 7000, 5200, 6500, 4800, 7200, 5300]
}

df_51 = pd.DataFrame(data_51)
display(df_51)

       Nome  Idade  Salário
0     Alice     28     5000
1       Bob     34     6000
2   Charlie     29     4500
3     David     42     8000
4      Emma     26     5500
5     Frank     35     7000
6      Gina     31     5200
7    Hannah     38     6500
8      Ivan     25     4800
9      Jack     33     7200
10    Katie     30     5300

a) Selecione os funcionários com idade superior a 35.

In [661]:
# RESPOSTA 51 LETRA A

b) Calcule a média salarial dos funcionários com idade inferior a 30.

In [662]:
# RESPOSTA 51 LETRA B

c) Ordene o DataFrame em ordem crescente com base no salário.

In [663]:
# RESPOSTA 51 LETRA C

d) Adicione uma coluna chamada "Bônus" que contenha 15% do salário de cada funcionário.

In [664]:
# RESPOSTA 51 LETRA D

# Exercício 52:

Considere o seguinte DataFrame df_52:

In [665]:
data_52 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos', 'Lara', 'Pedro', 'Mariana', 'Paulo', 'Bianca', 'Hugo', 'Fernanda'],
    'Matemática': [8, 7, 10, 9, 6, 9, 8, 7, 9, 8, 9, 7],
    'Português': [9, 6, 8, 10, 7, 7, 9, 8, 6, 9, 8, 7],
    'História': [7, 8, 6, 9, 5, 8, 6, 9, 8, 7, 7, 6]
}

df_52 = pd.DataFrame(data_52)
display(df_52)

       Aluno  Matemática  Português  História
0       João           8          9         7
1      Maria           7          6         8
2       José          10          8         6
3        Ana           9         10         9
4     Carlos           6          7         5
5       Lara           9          7         8
6      Pedro           8          9         6
7    Mariana           7          8         9
8      Paulo           9          6         8
9     Bianca           8          9         7
10      Hugo           9          8         7
11  Fernanda           7          7         6

a) Crie uma nova coluna chamada "Média" que contenha a média das notas de cada aluno.

In [666]:
# RESPOSTA 52 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Média".

In [667]:
# RESPOSTA 52 LETRA B

c) Identifique o aluno que obteve a maior nota em Matemática.

In [668]:
# RESPOSTA 52 LETRA C

d) Adicione uma coluna chamada "Situação" que contenha "Aprovado" para alunos com média >= 7 e "Reprovado" para alunos com média < 7.

In [669]:
# RESPOSTA 52 LETRA D

# Exercício 53:

Considere o seguinte DataFrame df_53:

In [670]:
data_53 = {
    'Produto': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'],
    'Vendas2019': [1000, 1200, 800, 950, 1100, 1300, 850, 920, 1120, 780, 1020, 970, 1450, 880, 1100],
    'Vendas2020': [1050, 1250, 820, 900, 1150, 1350, 820, 950, 1100, 750, 1000, 900, 1500, 900, 1150]
}

df_53 = pd.DataFrame(data_53)
display(df_53)

   Produto  Vendas2019  Vendas2020
0        A        1000        1050
1        B        1200        1250
2        C         800         820
3        D         950         900
4        E        1100        1150
5        F        1300        1350
6        G         850         820
7        H         920         950
8        I        1120        1100
9        J         780         750
10       K        1020        1000
11       L         970         900
12       M        1450        1500
13       N         880         900
14       O        1100        1150

a) Crie uma coluna chamada "Crescimento" que contenha a diferença percentual entre as vendas de 2020 e 2019 para cada produto.

In [671]:
# RESPOSTA 53 LETRA A

b) Identifique o produto que teve o menor crescimento de vendas.

In [672]:
# RESPOSTA 53 LETRA B

c) Adicione uma coluna chamada "Total_Vendas" que contenha a soma das vendas de 2019 e 2020 para cada produto.

In [673]:
# RESPOSTA 53 LETRA C

d) Ordene o DataFrame em ordem crescente com base no total de vendas.

In [674]:
# RESPOSTA 53 LETRA D

# Exercício 54:

Considere o seguinte DataFrame df_54:

In [675]:
data_54 = {
    'Data': ['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08', '2023-06-09', '2023-06-10'],
    'Vendas': [1000, 1200, 800, 950, 1100, 1300, 850, 920, 1120, 780]
}

df_54 = pd.DataFrame(data_54)
display(df_54)

         Data  Vendas
0  2023-06-01    1000
1  2023-06-02    1200
2  2023-06-03     800
3  2023-06-04     950
4  2023-06-05    1100
5  2023-06-06    1300
6  2023-06-07     850
7  2023-06-08     920
8  2023-06-09    1120
9  2023-06-10     780

a) Converta a coluna 'Data' para o tipo datetime.

In [676]:
# RESPOSTA 54 LETRA A

b) Crie uma nova coluna chamada "Dia_da_Semana" que contenha o dia da semana (em formato texto) para cada data.

In [677]:
# RESPOSTA 54 LETRA B

c) Identifique o dia da semana em que foram registradas as maiores vendas.

In [678]:
# RESPOSTA 54 LETRA C

d) Adicione uma coluna chamada "Meta_Diária" que contenha a média das vendas diárias.

In [679]:
# RESPOSTA 54 LETRA D

# Exercício 55:

Considere o seguinte DataFrame df_55:

In [680]:
data_55 = {
    'Time': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T'],
    'Gols': [3, 2, 2, 4, 1, 3, 2, 5, 3, 2, 1, 2, 4, 3, 5, 2, 1, 2, 3, 4],
    'Contra': [2, 1, 3, 2, 4, 2, 3, 4, 2, 3, 5, 3, 1, 2, 3, 4, 3, 1, 2, 4]
}

df_55 = pd.DataFrame(data_55)
display(df_55)

   Time  Gols  Contra
0     A     3       2
1     B     2       1
2     C     2       3
3     D     4       2
4     E     1       4
5     F     3       2
6     G     2       3
7     H     5       4
8     I     3       2
9     J     2       3
10    K     1       5
11    L     2       3
12    M     4       1
13    N     3       2
14    O     5       3
15    P     2       4
16    Q     1       3
17    R     2       1
18    S     3       2
19    T     4       4

a) Crie uma nova coluna chamada "Saldo_de_Gols" que contenha a diferença entre os gols marcados e os gols sofridos por cada time.

In [681]:
# RESPOSTA 55 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Saldo_de_Gols".

In [682]:
# RESPOSTA 55 LETRA B

c) Identifique o time com o menor saldo de gols.

In [683]:
# RESPOSTA 55 LETRA C

d) Adicione uma coluna chamada "Aproveitamento" que contenha a porcentagem de aproveitamento de cada time (Gols / (Gols + Contra)).

In [684]:
# RESPOSTA 55 LETRA D

# Exercício 56:

Considere o seguinte DataFrame df_56:

In [685]:
data_56 = {
    'Produto': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T'],
    'Preço': [10, 20, 15, 25, 30, 18, 22, 27, 12, 28, 20, 16, 30, 25, 22, 14, 30, 24, 18, 20],
    'Vendas': [100, 80, 120, 70, 90, 110, 75, 85, 150, 50, 90, 130, 65, 105, 120, 80, 110, 95, 70, 85]
}

df_56 = pd.DataFrame(data_56)
display(df_56)

   Produto  Preço  Vendas
0        A     10     100
1        B     20      80
2        C     15     120
3        D     25      70
4        E     30      90
5        F     18     110
6        G     22      75
7        H     27      85
8        I     12     150
9        J     28      50
10       K     20      90
11       L     16     130
12       M     30      65
13       N     25     105
14       O     22     120
15       P     14      80
16       Q     30     110
17       R     24      95
18       S     18      70
19       T     20      85

a) Crie uma nova coluna chamada "Receita" que contenha o valor total de receita (preço * vendas) para cada produto.

In [686]:
# RESPOSTA 56 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Receita".

In [687]:
# RESPOSTA 56 LETRA B

c) Identifique os 5 produtos que geraram maior receita.

In [688]:
# RESPOSTA 56 LETRA C

d) Adicione uma coluna chamada "Participação" que contenha a porcentagem de participação de cada produto na receita total.

In [689]:
# RESPOSTA 56 LETRA D

# Exercício 57:

Considere o seguinte DataFrame df_57:

In [690]:
data_57 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos', 'Lara', 'Pedro', 'Mariana', 'Paulo', 'Bianca', 'Hugo', 'Fernanda', 'Juliana', 'Ricardo', 'Thiago'],
    'Faltas': [2, 3, 1, 4, 0, 2, 1, 3, 0, 1, 2, 0, 3, 1, 0],
    'Atrasos': [0, 1, 2, 0, 3, 1, 0, 2, 1, 0, 1, 0, 2, 1, 0],
    'Notas': [8, 7, 9, 6, 10, 9, 8, 7, 9, 8, 7, 9, 8, 6, 7]
}

df_57 = pd.DataFrame(data_57)
display(df_57)

       Aluno  Faltas  Atrasos  Notas
0       João       2        0      8
1      Maria       3        1      7
2       José       1        2      9
3        Ana       4        0      6
4     Carlos       0        3     10
5       Lara       2        1      9
6      Pedro       1        0      8
7    Mariana       3        2      7
8      Paulo       0        1      9
9     Bianca       1        0      8
10      Hugo       2        1      7
11  Fernanda       0        0      9
12   Juliana       3        2      8
13   Ricardo       1        1      6
14    Thiago       0        0      7

a) Crie uma nova coluna chamada "Nota_Final" que contenha a média ponderada das notas dos alunos, considerando peso 3 para as notas e peso 1 para as faltas e atrasos.

In [691]:
# RESPOSTA 57 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Nota_Final".

In [692]:
# RESPOSTA 57 LETRA B

c) Identifique o aluno com a maior nota final.

In [693]:
# RESPOSTA 57 LETRA C

d) Adicione uma coluna chamada "Situação" que contenha "Aprovado" para alunos com média >= 7 e "Reprovado" para alunos com média < 7.

In [694]:
# RESPOSTA 57 LETRA D

# Exercício 58:

Considere o seguinte DataFrame df_58:

In [695]:
data_58 = {
    'Time': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T'],
    'Gols': [3, 2, 2, 4, 1, 3, 2, 5, 3, 2, 1, 2, 4, 3, 5, 2, 1, 2, 3, 4],
    'Contra': [2, 1, 3, 2, 4, 2, 3, 4, 2, 3, 5, 3, 1, 2, 3, 4, 3, 1, 2, 4]
}

df_58 = pd.DataFrame(data_58)
display(df_58)

   Time  Gols  Contra
0     A     3       2
1     B     2       1
2     C     2       3
3     D     4       2
4     E     1       4
5     F     3       2
6     G     2       3
7     H     5       4
8     I     3       2
9     J     2       3
10    K     1       5
11    L     2       3
12    M     4       1
13    N     3       2
14    O     5       3
15    P     2       4
16    Q     1       3
17    R     2       1
18    S     3       2
19    T     4       4


a) Crie uma nova coluna chamada "Saldo_de_Gols" que contenha a diferença entre os gols marcados e os gols sofridos por cada time.

In [696]:
# RESPOSTA 58 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Saldo_de_Gols".

In [697]:
# RESPOSTA 58 LETRA B

c) Identifique o time com o maior saldo de gols.

In [698]:
# RESPOSTA 58 LETRA C

d) Adicione uma coluna chamada "Aproveitamento" que contenha a porcentagem de aproveitamento de cada time (Gols / (Gols + Contra)).

In [699]:
# RESPOSTA 58 LETRA D

# Exercício 59:

Considere o seguinte DataFrame df_59:

In [700]:
data_59 = {
    'Produto': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T'],
    'Estoque': [100, 80, 120, 70, 90, 110, 75, 85, 150, 50, 90, 130, 65, 105, 120, 80, 110, 95, 70, 85],
    'Vendas': [20, 30, 25, 40, 15, 28, 33, 18, 50, 10, 30, 25, 45, 35, 40, 20, 25, 30, 18, 22]
}

df_59 = pd.DataFrame(data_59)
display(df_59)

   Produto  Estoque  Vendas
0        A      100      20
1        B       80      30
2        C      120      25
3        D       70      40
4        E       90      15
5        F      110      28
6        G       75      33
7        H       85      18
8        I      150      50
9        J       50      10
10       K       90      30
11       L      130      25
12       M       65      45
13       N      105      35
14       O      120      40
15       P       80      20
16       Q      110      25
17       R       95      30
18       S       70      18
19       T       85      22

a) Crie uma nova coluna chamada "Estoque_Atual" que contenha a quantidade atual de produtos em estoque (Estoque - Vendas).

In [701]:
# RESPOSTA 59 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Estoque_Atual".

In [702]:
# RESPOSTA 59 LETRA B

c) Identifique o produto que possui o menor estoque atual.

In [703]:
# RESPOSTA 59 LETRA C

d) Adicione uma coluna chamada "Disponibilidade" que contenha a porcentagem de produtos disponíveis em estoque (Estoque_Atual / Estoque).

In [704]:
# RESPOSTA 59 LETRA D

# Exercício 60:

Considere o seguinte DataFrame df_60:

In [705]:
data_60 = {
    'Aluno': ['João', 'Maria', 'José', 'Ana', 'Carlos', 'Lara', 'Pedro', 'Mariana', 'Paulo', 'Bianca', 'Hugo', 'Fernanda', 'Juliana', 'Ricardo', 'Thiago', 'Laura', 'Daniel', 'Isabela', 'Rafael', 'Gabriela'],
    'Faltas': [2, 3, 1, 4, 0, 2, 1, 3, 0, 1, 2, 0, 3, 1, 0, 2, 1, 3, 0, 1],
    'Atrasos': [0, 1, 2, 0, 3, 1, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 1, 0],
    'Notas': [8, 7, 9, 6, 10, 9, 8, 7, 9, 8, 7, 9, 8, 6, 7, 8, 7, 9, 8, 7]
}

df_60 = pd.DataFrame(data_60)
display(df_60)

       Aluno  Faltas  Atrasos  Notas
0       João       2        0      8
1      Maria       3        1      7
2       José       1        2      9
3        Ana       4        0      6
4     Carlos       0        3     10
5       Lara       2        1      9
6      Pedro       1        0      8
7    Mariana       3        2      7
8      Paulo       0        1      9
9     Bianca       1        0      8
10      Hugo       2        1      7
11  Fernanda       0        0      9
12   Juliana       3        2      8
13   Ricardo       1        1      6
14    Thiago       0        0      7
15     Laura       2        1      8
16    Daniel       1        0      7
17   Isabela       3        2      9
18    Rafael       0        1      8
19  Gabriela       1        0      7

a) Crie uma nova coluna chamada "Nota_Final" que contenha a média ponderada das notas dos alunos, considerando peso 3 para as notas e peso 1 para as faltas e atrasos.

In [706]:
# RESPOSTA 60 LETRA A

b) Ordene o DataFrame em ordem decrescente com base na coluna "Nota_Final".

In [707]:
# RESPOSTA 60 LETRA B

c) Identifique os 5 alunos com as maiores notas finais.

In [708]:
# RESPOSTA 60 LETRA C

d) Adicione uma coluna chamada "Situação" que contenha "Aprovado" para alunos com média >= 7 e "Reprovado" para alunos com média < 7.

In [709]:
# RESPOSTA 60 LETRA D